# Generated by Django 3.1.3 on 2020-11-24 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='initial_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sold'),
        ),
    ]
