# Generated by Django 3.1.3 on 2020-11-24 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0002_salesproduct_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='add_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now_add=True, unique=True, verbose_name='date sale'),
        ),
    ]
