# Generated by Django 3.1.3 on 2020-11-30 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0004_remove_sales_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@ +-]+$', 'This value may contain only letters, numbers and @/./+/-/_ characters')], verbose_name='Name'),
        ),
    ]
