# Generated by Django 3.1.4 on 2020-12-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0007_auto_20201201_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='price_per_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price per Product'),
        ),
    ]
