# Generated by Django 3.1.4 on 2020-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0008_auto_20201202_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price Total'),
        ),
    ]
