# Generated by Django 3.1.4 on 2020-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0010_sales_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='products',
        ),
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
