# Generated by Django 3.1.4 on 2020-12-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugaspi', '0011_auto_20201202_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
